### ISSUE TITLE
URLParams option should take a string instead

### ISSUE THREAD

**Issue by nhooyr** [cdr/hat#21]
If they want to use url.Values, they can, and then encode.

It just makes the API really verbose if they just want to encode a few simple parameters.

**Comment by ammario** [comment]
If they want to provide params that way, they can just append to the path?

**Comment by nhooyr** [comment]
Should be documented that works. Seems unexpected imo to call it a path then when it's really a URL. At that point, we don't even need the URLParams option.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
